"""Shared paths and verified Laya adapters for the local event-mesh experiment."""
from __future__ import annotations

import hashlib
import json
import math
import os
import random
import shutil
import tempfile
import warnings
from pathlib import Path
from typing import Any, Iterable

ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "configs" / "experiment.yaml"
BASE_MODEL_DIR = ROOT / "models" / "laya-multilingual"
OUTPUT_DIR = ROOT / "outputs"
DATA_DIR = ROOT / "data"

# Keep every cache generated by our code inside this inspectable project.
os.environ.setdefault("XDG_CACHE_HOME", str(ROOT / ".cache"))
os.environ.setdefault("HF_HOME", str(ROOT / ".cache" / "huggingface"))
os.environ.setdefault("HF_HUB_CACHE", str(ROOT / ".cache" / "huggingface" / "hub"))
os.environ.setdefault("HF_DATASETS_CACHE", str(ROOT / ".cache" / "huggingface" / "datasets"))
os.environ.setdefault("TORCH_HOME", str(ROOT / ".cache" / "torch"))
os.environ.setdefault("PYTORCH_ENABLE_MPS_FALLBACK", "1")
os.environ.setdefault("USE_TF", "0")

ROUTES = (
    "order-processing",
    "payment-operations",
    "logistics",
    "inventory-management",
    "customer-support",
    "fraud-review",
)
QUESTION_ID = "route"
ROUTING_QUESTION = {
    QUESTION_ID: {
        "type": "choice",
        "instructions": (
            "Which consumer service should receive this Solace event? Prefer schema, event_type, "
            "and payload meaning over a conflicting legacy topic."
        ),
        "criteria": {
            "order-processing": "order creation, amendment, cancellation, or validation",
            "payment-operations": "payment authorization, settlement, failure, refund, or reconciliation",
            "logistics": "shipment, carrier, delivery, customs, or fulfilment movement",
            "inventory-management": "warehouse stock reservation, count, replenishment, or correction",
            "customer-support": "customer ticket, complaint, service request, or human follow-up",
            "fraud-review": "suspected fraud, account takeover, payment abuse, or security alert",
        },
    }
}


def load_config(path: Path | str = CONFIG_PATH) -> dict[str, Any]:
    import yaml

    with Path(path).open(encoding="utf-8") as handle:
        config = yaml.safe_load(handle)
    if not isinstance(config, dict):
        raise ValueError(f"Configuration must be a mapping: {path}")
    return config


def read_jsonl(path: Path | str) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    with Path(path).open(encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, 1):
            if not line.strip():
                continue
            try:
                value = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"{path}:{line_number}: invalid JSON: {exc}") from exc
            if not isinstance(value, dict):
                raise ValueError(f"{path}:{line_number}: expected a JSON object")
            records.append(value)
    return records


def write_jsonl(path: Path | str, records: Iterable[dict[str, Any]]) -> None:
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open("w", encoding="utf-8") as handle:
        for record in records:
            handle.write(json.dumps(record, ensure_ascii=False, sort_keys=True) + "\n")


def atomic_write_json(path: Path | str, value: Any) -> None:
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{destination.name}.", suffix=".tmp", dir=destination.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            json.dump(value, handle, ensure_ascii=False, indent=2, sort_keys=True)
            handle.write("\n")
        os.replace(temporary, destination)
    except BaseException:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
        raise


def update_manifest(**sections: Any) -> dict[str, Any]:
    path = OUTPUT_DIR / "run_manifest.json"
    manifest: dict[str, Any] = {}
    if path.exists():
        with path.open(encoding="utf-8") as handle:
            manifest = json.load(handle)
    manifest.update(sections)
    atomic_write_json(path, manifest)
    return manifest


def state_fingerprint(state: dict[str, Any]) -> str:
    encoded = json.dumps(state, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(encoded).hexdigest()


def question_contract_hash() -> str:
    encoded = json.dumps(ROUTING_QUESTION, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(encoded).hexdigest()


def select_device(requested: str = "auto"):
    import torch

    if requested not in {"auto", "mps", "cpu"}:
        raise ValueError(f"device must be auto, mps, or cpu; got {requested!r}")
    wants_mps = requested in {"auto", "mps"}
    available = bool(
        hasattr(torch.backends, "mps")
        and torch.backends.mps.is_built()
        and torch.backends.mps.is_available()
    )
    if wants_mps and available:
        try:
            probe = torch.ones(1, device="mps")
            if float((probe + 1).cpu().item()) != 2.0:
                raise RuntimeError("MPS arithmetic probe returned an unexpected value")
            del probe
            return torch.device("mps")
        except RuntimeError as exc:
            warnings.warn(f"MPS was reported available but failed its tensor probe; using CPU: {exc}")
            return torch.device("cpu")
    if requested == "mps":
        warnings.warn("MPS was explicitly requested but is unavailable; using CPU.")
    elif requested == "auto":
        warnings.warn("MPS is unavailable; using the CPU correctness path.")
    return torch.device("cpu")


def clear_device_cache(device) -> None:
    import gc
    import torch

    gc.collect()
    if device.type == "mps" and hasattr(torch, "mps"):
        torch.mps.empty_cache()


def mps_memory() -> dict[str, int] | None:
    import torch

    if not (hasattr(torch.backends, "mps") and torch.backends.mps.is_available()):
        return None
    result: dict[str, int] = {}
    for name in ("current_allocated_memory", "driver_allocated_memory", "recommended_max_memory"):
        function = getattr(torch.mps, name, None)
        if callable(function):
            try:
                result[name] = int(function())
            except RuntimeError:
                pass
    return result or None


def require_free_disk(minimum_gb: float) -> float:
    free_gb = shutil.disk_usage(ROOT).free / (1024**3)
    if free_gb < minimum_gb:
        raise RuntimeError(
            f"Only {free_gb:.1f} GiB is free at {ROOT}; at least {minimum_gb:.1f} GiB is required."
        )
    return free_gb


def build_training_item(tokenizer, model_config: dict[str, Any], record: dict[str, Any]) -> dict[str, Any]:
    """Adapt one local row with the official Apple trainer's typed-choice encoding."""
    from laya.common import QTYPES, build_sequence, render_options

    question = record["questions"][QUESTION_ID]
    gold = record["gold"][QUESTION_ID]
    if question["type"] != "choice":
        raise ValueError(f"{record['id']}: this experiment expects a typed choice")
    criteria = question["criteria"]
    keys = list(criteria)
    target = [float(gold["probabilities"].get(key, 0.0)) for key in keys]
    total = sum(target)
    if not math.isfinite(total) or total <= 0:
        raise ValueError(f"{record['id']}: invalid target distribution")
    target = [value / total for value in target]
    internal = {"t": "choice", "ins": question["instructions"], "crit": criteria}
    sequence, markers = build_sequence(
        tokenizer,
        record["state"],
        internal,
        int(model_config["max_len"]),
        int(model_config["head_max_len"]),
    )
    expected_markers = len(render_options(internal))
    if len(markers) != expected_markers:
        raise ValueError(
            f"{record['id']}: only {len(markers)}/{expected_markers} option markers fit; "
            "increase max_length or reduce head_max_length"
        )
    return {
        "id": record["id"],
        "ids": sequence,
        "markers": markers,
        "qtype": QTYPES["choice"],
        "target": target,
        "label": int(max(range(len(target)), key=target.__getitem__)),
        "language": record["language"],
        "challenge_tags": list(record.get("challenge_tags", [])),
    }


def collate_training_items(items: list[dict[str, Any]], pad_id: int, fixed_length: int) -> dict[str, Any]:
    """Pad every batch to one fixed shape to bound MPS graph-cache growth."""
    import torch

    if not items:
        raise ValueError("cannot collate an empty batch")
    if any(len(item["ids"]) > fixed_length for item in items):
        raise ValueError("an encoded sequence exceeds fixed_length")
    batch_size = len(items)
    kmax = max(len(item["markers"]) for item in items)
    input_ids = torch.full((batch_size, fixed_length), pad_id, dtype=torch.long)
    attention_mask = torch.zeros((batch_size, fixed_length), dtype=torch.long)
    marker_pos = torch.zeros((batch_size, kmax), dtype=torch.long)
    marker_mask = torch.zeros((batch_size, kmax), dtype=torch.bool)
    target = torch.zeros((batch_size, kmax), dtype=torch.float32)
    for index, item in enumerate(items):
        length = len(item["ids"])
        input_ids[index, :length] = torch.as_tensor(item["ids"], dtype=torch.long)
        attention_mask[index, :length] = 1
        marker_count = len(item["markers"])
        marker_pos[index, :marker_count] = torch.as_tensor(item["markers"], dtype=torch.long)
        marker_mask[index, :marker_count] = True
        target[index, :marker_count] = torch.as_tensor(item["target"], dtype=torch.float32)
    return {
        "input_ids": input_ids,
        "attention_mask": attention_mask,
        "marker_pos": marker_pos,
        "marker_mask": marker_mask,
        "target": target,
        "qtype": torch.as_tensor([item["qtype"] for item in items], dtype=torch.long),
        "labels": torch.as_tensor([item["label"] for item in items], dtype=torch.long),
    }


def load_trainable_model(base_model_dir: Path, max_length: int, head_max_length: int):
    """Construct and populate the official DecisionModel from a local Laya checkpoint."""
    from safetensors.torch import load_file
    from transformers import AutoTokenizer
    from laya.common import build_model

    with (base_model_dir / "rl_agent_config.json").open(encoding="utf-8") as handle:
        model_config = json.load(handle)
    model_config.update(
        {
            "max_len": int(max_length),
            "head_max_len": int(head_max_length),
            "max_tokens_per_batch": int(max_length),
        }
    )
    tokenizer = AutoTokenizer.from_pretrained(base_model_dir / "tokenizer", local_files_only=True)
    model = build_model(
        model_config,
        encoder_dir=base_model_dir / "encoder",
        pretrained=False,
    )
    model.load_state_dict(load_file(str(base_model_dir / "model.safetensors")), strict=True)
    return model.float(), tokenizer, model_config


def freeze_model(model, strategy: str) -> list[Any]:
    """Apply the configured conservative adaptation strategy and return trainable parameters."""
    for parameter in model.parameters():
        parameter.requires_grad = True
    if strategy == "head_only":
        for parameter in model.encoder.parameters():
            parameter.requires_grad = False
    elif strategy in {"last_1", "last_2"}:
        for parameter in model.encoder.parameters():
            parameter.requires_grad = False
        layer_count = int(strategy.rsplit("_", 1)[1])
        layers = getattr(model.encoder, "layers", None)
        if layers is None and hasattr(model.encoder, "encoder"):
            layers = getattr(model.encoder.encoder, "layer", None) or getattr(model.encoder.encoder, "layers", None)
        if layers is None:
            raise ValueError("Could not locate encoder blocks for partial unfreezing; use head_only")
        for layer in list(layers)[-layer_count:]:
            for parameter in layer.parameters():
                parameter.requires_grad = True
    else:
        raise ValueError(f"Unsupported freeze_strategy: {strategy}")
    trainable = [parameter for parameter in model.parameters() if parameter.requires_grad]
    if not trainable:
        raise RuntimeError("Freeze strategy left no trainable parameters")
    return trainable


def parameter_counts(model) -> dict[str, int]:
    total = sum(parameter.numel() for parameter in model.parameters())
    trainable = sum(parameter.numel() for parameter in model.parameters() if parameter.requires_grad)
    return {"total": int(total), "trainable": int(trainable), "frozen": int(total - trainable)}


def set_seed(seed: int) -> None:
    import numpy as np
    import torch

    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.use_deterministic_algorithms(True, warn_only=True)


def probabilities_from_answer(answer: dict[str, Any]) -> list[float]:
    values = [float(answer["probabilities"].get(route, 0.0)) for route in ROUTES]
    total = sum(values)
    if total <= 0 or not all(math.isfinite(value) for value in values):
        raise ValueError(f"Invalid Laya probabilities: {values}")
    return [value / total for value in values]
